services:
  notificationservice:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: notificationservice
    environment:
      - RabbitMQ__HostName=rabbitmq
      - RabbitMQ__Port=5672
      - RabbitMQ__UserName=guest
      - RabbitMQ__Password=guest
    networks:
      - inventoryapi_default
    restart: on-failure

networks:
  inventoryapi_default:
    external: true